.intel_syntax noprefix
.text
	# Generated by our language compiler

.global _start
_start:
	call main
	mov rdi, rax
	mov rax, 60
	syscall

	# Procedure: main
.global main
main:
	# Procedure prologue
	push rbp
	mov rbp, rsp
	# Compound statement
	# Return statement
	# TODO: Object method calls not yet supported
