#include "ast.hpp"
#include "defines.hpp"
#include "generator.hpp"
#include "memory.hpp"
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>

static bool generate_declaration_win(x86_windows_generator &cg, ast_node *decl);
static bool generate_procedure_win(x86_windows_generator &cg, ast_decl_procedure *proc);
static bool generate_statement_win(x86_windows_generator &cg, ast_node *stmt);
static bool generate_expression_win(x86_windows_generator &cg, ast_node *expr);
static bool generate_global_variable_win(x86_windows_generator &cg, ast_decl_variable *var_decl);
static bool generate_literal_win(x86_windows_generator &cg, ast_expr_literal *lit);
static bool generate_identifier_win(x86_windows_generator &cg, ast_expr_identifier *ident);
static bool generate_binary_expression_win(x86_windows_generator &cg, ast_expr_binary *binary);
static bool generate_function_call_win(x86_windows_generator &cg, ast_expr_call *call);
static bool generate_print_call_win(x86_windows_generator &cg, ast_expr_call *call);
static bool generate_println_call_win(x86_windows_generator &cg, ast_expr_call *call);
static bool generate_exit_call_win(x86_windows_generator &cg, int exit_code);

static void emit_comment(x86_windows_generator &cg, const char *comment, ...);
static void emit_label(x86_windows_generator &cg, const char *label);
static void emit_directive(x86_windows_generator &cg, const char *directive);
static void emit_instruction(x86_windows_generator &cg, const char *instr);
static void emit_instruction_reg(x86_windows_generator &cg, const char *instr, x86_windows_register r);
static void emit_instruction_reg_reg(x86_windows_generator &cg, const char *instr, x86_windows_register dst,
                                     x86_windows_register src);
static void emit_instruction_reg_imm(x86_windows_generator &cg, const char *instr, x86_windows_register r, i32 imm);
static void emit_instruction_reg_mem(x86_windows_generator &cg, const char *instr, x86_windows_register r,
                                     x86_windows_register base, i32 offset);

static const char *reg_name_64_win(x86_windows_register r);
static const char *reg_name_32_win(x86_windows_register r);
static char *generate_label_win(x86_windows_generator &cg, const char *prefix);
static const char *builtin_type_size_suffix_win(builtin_type type);
static const char *reg_name_for_type_win(x86_windows_register r, builtin_type type);
extern const char *binary_op_to_string(binary_op op);

bool x86_windows_generator_init(x86_windows_generator &cg, arena &memory, FILE *out_file) {
    cg.memory = &memory;
    cg.out_file = out_file;
    cg.stack_offset = 0;
    cg.label_counter = 0;
    cg.shadow_space = 32; // Windows x64 requires 32 bytes of shadow space
    cg.current_procedure = nullptr;
    cg.in_procedure = false;

    return true;
}

void x86_windows_generator_deinit(x86_windows_generator &cg) {
    cg = {};
}

bool x86_windows_generate_asm(x86_windows_generator &cg, ast_node *program) {
    if (!program || program->type != ast_node_type::TRANSLATION_UNIT) {
        return false;
    }

    ast_translation_unit *unit = (ast_translation_unit *)program;

    // Generate assembly header for Windows
    fprintf(cg.out_file, ".intel_syntax noprefix\n");
    fprintf(cg.out_file, ".text\n");
    fprintf(cg.out_file, "\t# Generated by our language compiler for Windows x64\n\n");

    // Windows entry point
    fprintf(cg.out_file, ".global main\n");
    fprintf(cg.out_file, ".def main; .scl 2; .type 32; .endef\n");
    fprintf(cg.out_file, "main:\n");

    // Windows calling convention prologue
    emit_comment(cg, "Main function prologue (Windows x64)");
    emit_instruction_reg(cg, "push", x86_windows_register::RBP);
    emit_instruction_reg_reg(cg, "mov", x86_windows_register::RBP, x86_windows_register::RSP);
    emit_instruction_reg_imm(cg, "sub", x86_windows_register::RSP, 40); // Shadow space + alignment

    // Call user main if it exists, otherwise generate inline code
    bool has_user_main = false;
    for (u32 i = 0; i < unit->declaration_count; i++) {
        ast_node *decl = unit->declarations[i];
        if (decl->type == ast_node_type::DECL_PROCEDURE) {
            ast_decl_procedure *proc = (ast_decl_procedure *)decl;
            if (strncmp(proc->name, "main", proc->name_len) == 0 && proc->name_len == 4) {
                has_user_main = true;
                break;
            }
        }
    }

    if (has_user_main) {
        fprintf(cg.out_file, "\tcall user_main\n");
    }

    // Main function epilogue
    emit_comment(cg, "Main function epilogue");
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0); // Return 0 by default
    emit_instruction_reg_reg(cg, "mov", x86_windows_register::RSP, x86_windows_register::RBP);
    emit_instruction_reg(cg, "pop", x86_windows_register::RBP);
    emit_instruction(cg, "ret");
    fprintf(cg.out_file, "\n");

    // Process all declarations
    for (u32 i = 0; i < unit->declaration_count; i++) {
        ast_node *decl = unit->declarations[i];

        if (decl->type == ast_node_type::DECL_PROCEDURE) {
            if (!generate_procedure_win(cg, (ast_decl_procedure *)decl)) {
                return false;
            }
        } else if (decl->type == ast_node_type::DECL_VARIABLE) {
            if (!generate_global_variable_win(cg, (ast_decl_variable *)decl)) {
                return false;
            }
        }
    }

    return true;
}

static bool generate_procedure_win(x86_windows_generator &cg, ast_decl_procedure *proc) {
    // Procedure name from token
    char proc_name[256];
    snprintf(proc_name, sizeof(proc_name), "%.*s", proc->name_len, proc->name);

    // Rename main to user_main to avoid conflict with our main
    if (strcmp(proc_name, "main") == 0) {
        strcpy(proc_name, "user_main");
    }

    cg.current_procedure = proc_name;
    cg.in_procedure = true;
    cg.stack_offset = 0;

    // Procedure declaration without body (forward declaration)
    if (!proc->body) {
        emit_comment(cg, "Forward declaration - no code generated");
        return true;
    }

    emit_comment(cg, "Procedure: %s", proc_name);

    // Make procedure globally visible
    fprintf(cg.out_file, ".global %s\n", proc_name);
    fprintf(cg.out_file, ".def %s; .scl 2; .type 32; .endef\n", proc_name);
    emit_label(cg, proc_name);

    // Windows x64 procedure prologue
    emit_comment(cg, "Procedure prologue (Windows x64)");
    emit_instruction_reg(cg, "push", x86_windows_register::RBP); // Save old base pointer
    emit_instruction_reg_reg(cg, "mov", x86_windows_register::RBP,
                             x86_windows_register::RSP);                             // Set up new base pointer
    emit_instruction_reg_imm(cg, "sub", x86_windows_register::RSP, cg.shadow_space); // Allocate shadow space

    // TODO: Allocate space for local variables
    // emit_instruction_reg_imm_win(cg, "sub", reg::RSP, local_var_space);

    // Generate procedure body
    if (!generate_statement_win(cg, proc->body)) {
        return false;
    }

    // Procedure epilogue (in case there's no explicit return)
    emit_comment(cg, "Procedure epilogue");
    emit_instruction_reg_reg(cg, "mov", x86_windows_register::RSP,
                             x86_windows_register::RBP);        // Restore stack pointer
    emit_instruction_reg(cg, "pop", x86_windows_register::RBP); // Restore base pointer
    emit_instruction(cg, "ret");                                // Return

    cg.in_procedure = false;
    cg.current_procedure = nullptr;

    return true;
}

static bool generate_statement_win(x86_windows_generator &cg, ast_node *stmt) {
    if (!stmt) return true;

    switch (stmt->type) {
    case ast_node_type::STMT_COMPOUND: {
        ast_stmt_compound *compound = (ast_stmt_compound *)stmt;
        emit_comment(cg, "Compound statement");

        for (u32 i = 0; i < compound->statement_count; i++) {
            if (!generate_statement_win(cg, compound->statements[i])) {
                return false;
            }
        }
        return true;
    }

    case ast_node_type::STMT_RETURN: {
        ast_stmt_return *ret = (ast_stmt_return *)stmt;
        emit_comment(cg, "Return statement");

        if (ret->value) {
            // Generate code for return value (result should be in RAX)
            if (!generate_expression_win(cg, ret->value)) {
                return false;
            }
            // Result is already in RAX, which is the return register
        } else {
            // Return void - set RAX to 0
            emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        }

        // Jump to procedure epilogue
        emit_instruction_reg_reg(cg, "mov", x86_windows_register::RSP, x86_windows_register::RBP);
        emit_instruction_reg(cg, "pop", x86_windows_register::RBP);
        emit_instruction(cg, "ret");
        return true;
    }

    case ast_node_type::STMT_EXPRESSION: {
        ast_stmt_expression *expr_stmt = (ast_stmt_expression *)stmt;
        emit_comment(cg, "Expression statement");
        return generate_expression_win(cg, expr_stmt->expression);
    }

    case ast_node_type::STMT_IF: {
        ast_stmt_if *if_stmt = (ast_stmt_if *)stmt;
        emit_comment(cg, "If statement");

        char *else_label = generate_label_win(cg, "else");
        char *end_label = generate_label_win(cg, "endif");

        // Generate condition
        if (!generate_expression_win(cg, if_stmt->condition)) {
            return false;
        }

        // Test result and jump if false
        emit_instruction_reg_imm(cg, "cmp", x86_windows_register::RAX, 0);
        fprintf(cg.out_file, "\tje %s\n", else_label);

        // Generate then block
        if (!generate_statement_win(cg, if_stmt->then_stmt)) {
            return false;
        }

        if (if_stmt->else_stmt) {
            fprintf(cg.out_file, "\tjmp %s\n", end_label);
            emit_label(cg, else_label);
            if (!generate_statement_win(cg, if_stmt->else_stmt)) {
                return false;
            }
            emit_label(cg, end_label);
        } else {
            emit_label(cg, else_label);
        }

        return true;
    }

    default:
        emit_comment(cg, "TODO: Statement type %d", (int)stmt->type);
        return true;
    }
}

static bool generate_expression_win(x86_windows_generator &cg, ast_node *expr) {
    if (!expr) {
        return false;
    }

    switch (expr->type) {
    case ast_node_type::EXPR_CALL:
        return generate_function_call_win(cg, (ast_expr_call *)expr);
    case ast_node_type::EXPR_LITERAL:
        return generate_literal_win(cg, (ast_expr_literal *)expr);
    case ast_node_type::EXPR_IDENTIFIER:
        return generate_identifier_win(cg, (ast_expr_identifier *)expr);
    case ast_node_type::EXPR_BINARY:
        return generate_binary_expression_win(cg, (ast_expr_binary *)expr);
    default:
        return false;
    }
}

static bool generate_global_variable_win(x86_windows_generator &cg, ast_decl_variable *var_decl) {
    char var_name[256];
    snprintf(var_name, sizeof(var_name), "%.*s", var_decl->name_len, var_decl->name);

    emit_comment(cg, "Global variable: %s", var_name);

    // Switch to data section
    fprintf(cg.out_file, ".section .data\n");

    // Make variable globally visible (Windows style)
    fprintf(cg.out_file, ".global %s\n", var_name);
    fprintf(cg.out_file, ".def %s; .scl 2; .type 32; .endef\n", var_name);
    emit_label(cg, var_name);

    // Initialize with value if present (same logic as Linux version)
    if (var_decl->initializer && var_decl->initializer->type == ast_node_type::EXPR_LITERAL) {
        ast_expr_literal *lit = (ast_expr_literal *)var_decl->initializer;

        switch (lit->type) {
        case literal_type::INTEGER: {
            char value_str[32];
            snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
            i32 value = atoi(value_str);
            fprintf(cg.out_file, "\t.long %d\n", value);
            break;
        }
        case literal_type::STRING: {
            // String literals go in .rdata (read-only data section on Windows)
            fprintf(cg.out_file, ".section .rdata\n");
            fprintf(cg.out_file, "\t.string ");

            // Print the string literal with quotes
            for (u32 i = 0; i < lit->value_len; i++) {
                fputc(lit->value[i], cg.out_file);
            }
            fprintf(cg.out_file, "\n");
            break;
        }
        case literal_type::BOOLEAN: {
            char value_str[8];
            snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
            bool is_true = (strncmp(value_str, "true", 4) == 0);
            fprintf(cg.out_file, "\t.byte %d\n", is_true ? 1 : 0);
            break;
        }
        default:
            fprintf(cg.out_file, "\t.long 0\n"); // Default initialization
            break;
        }
    } else {
        // Default initialization
        fprintf(cg.out_file, "\t.long 0\n");
    }

    // Switch back to text section
    fprintf(cg.out_file, ".section .text\n");

    return true;
}

static bool generate_literal_win(x86_windows_generator &cg, ast_expr_literal *lit) {
    switch (lit->type) {
    case literal_type::INTEGER: {
        char value_str[32];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
        i32 value = atoi(value_str);

        emit_comment(cg, "Integer literal: %d", value);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, value);
        return true;
    }

    case literal_type::BOOLEAN: {
        char value_str[8];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
        bool is_true = (strncmp(value_str, "true", 4) == 0);

        emit_comment(cg, "Boolean literal: %s", is_true ? "true" : "false");
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, is_true ? 1 : 0);
        return true;
    }

    case literal_type::STRING: {
        emit_comment(cg, "String literal: %.*s", lit->value_len, lit->value);

        static int string_literal_counter = 0;

        // Generate string constant in .rdata section (Windows)
        fprintf(cg.out_file, "\t.section .rdata\n");
        fprintf(cg.out_file, ".LS%d:\n", string_literal_counter);

        // Remove quotes and handle escape sequences
        const char *str_content = lit->value + 1; // Skip opening quote
        u32 content_len = lit->value_len - 2;     // Remove both quotes

        fprintf(cg.out_file, "\t.string \"");
        for (u32 i = 0; i < content_len; i++) {
            char c = str_content[i];
            if (c == '\\' && i + 1 < content_len) {
                char next = str_content[i + 1];
                switch (next) {
                case 'n':
                    fprintf(cg.out_file, "\\n");
                    i++;
                    break;
                case 't':
                    fprintf(cg.out_file, "\\t");
                    i++;
                    break;
                case 'r':
                    fprintf(cg.out_file, "\\r");
                    i++;
                    break;
                case '\\':
                    fprintf(cg.out_file, "\\\\");
                    i++;
                    break;
                case '"':
                    fprintf(cg.out_file, "\\\"");
                    i++;
                    break;
                default:
                    fprintf(cg.out_file, "%c", c);
                    break;
                }
            } else {
                fprintf(cg.out_file, "%c", c);
            }
        }
        fprintf(cg.out_file, "\"\n");

        fprintf(cg.out_file, "\t.text\n");

        // Load address of string into RAX
        fprintf(cg.out_file, "\tlea rax, .LS%d[rip]\n", string_literal_counter);

        string_literal_counter++;
        return true;
    }

    case literal_type::CHARACTER: {
        char value_str[8];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);

        char char_value = 0;
        if (lit->value_len >= 3) {
            char_value = lit->value[1];
        }

        emit_comment(cg, "Character literal: %c (%d)", char_value, (int)char_value);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, (i32)char_value);
        return true;
    }

    case literal_type::FLOAT: {
        char value_str[32];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);

        emit_comment(cg, "Float literal: %s (TODO: proper float handling)", value_str);
        i32 int_value = (i32)atof(value_str);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, int_value);
        return true;
    }

    default:
        emit_comment(cg, "TODO: Unsupported literal type %d", (int)lit->type);
        return false;
    }
}

static bool generate_identifier_win(x86_windows_generator &cg, ast_expr_identifier *ident) {
    char name[256];
    snprintf(name, sizeof(name), "%.*s", ident->name_len, ident->name);

    emit_comment(cg, "Variable access: %s", name);

    // For now, assume it's a global variable
    fprintf(cg.out_file, "\tmov rax, [%s]\n", name);

    return true;
}

static bool generate_binary_expression_win(x86_windows_generator &cg, ast_expr_binary *binary) {
    emit_comment(cg, "Binary expression: %s", binary_op_to_string(binary->op));

    // Generate right operand first
    if (!generate_expression_win(cg, binary->right)) {
        return false;
    }
    emit_instruction_reg(cg, "push", x86_windows_register::RAX); // Save right operand

    // Generate left operand
    if (!generate_expression_win(cg, binary->left)) {
        return false;
    }

    // Pop right operand into RCX
    emit_instruction_reg(cg, "pop", x86_windows_register::RCX);

    // Same binary operations as Linux version
    switch (binary->op) {
    case binary_op::ADD:
        emit_instruction_reg_reg(cg, "add", x86_windows_register::RAX, x86_windows_register::RCX);
        break;

    case binary_op::SUB:
        emit_instruction_reg_reg(cg, "sub", x86_windows_register::RAX, x86_windows_register::RCX);
        break;

    case binary_op::MUL:
        emit_instruction_reg_reg(cg, "imul", x86_windows_register::RAX, x86_windows_register::RCX);
        break;

    case binary_op::DIV:
        emit_comment(cg, "Division: clear RDX and divide");
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 0);
        fprintf(cg.out_file, "\tidiv rcx\n");
        break;

    case binary_op::MOD:
        emit_comment(cg, "Modulo: clear RDX and divide, result in RDX");
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 0);
        fprintf(cg.out_file, "\tidiv rcx\n");
        emit_instruction_reg_reg(cg, "mov", x86_windows_register::RAX, x86_windows_register::RDX);
        break;

    case binary_op::EQ:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmove rax, rdx\n");
        break;

    case binary_op::NE:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmovne rax, rdx\n");
        break;

    case binary_op::LT:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmovl rax, rdx\n");
        break;

    case binary_op::LE:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmovle rax, rdx\n");
        break;

    case binary_op::GT:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmovg rax, rdx\n");
        break;

    case binary_op::GE:
        emit_instruction_reg_reg(cg, "cmp", x86_windows_register::RAX, x86_windows_register::RCX);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RDX, 1);
        fprintf(cg.out_file, "\tcmovge rax, rdx\n");
        break;

    case binary_op::LOGICAL_AND:
        emit_comment(cg, "Logical AND");
        emit_instruction_reg_imm(cg, "cmp", x86_windows_register::RAX, 0);
        fprintf(cg.out_file, "\tje .L_and_false_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "cmp", x86_windows_register::RCX, 0);
        fprintf(cg.out_file, "\tje .L_and_false_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 1);
        fprintf(cg.out_file, "\tjmp .L_and_end_%d\n", cg.label_counter);
        fprintf(cg.out_file, ".L_and_false_%d:\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        fprintf(cg.out_file, ".L_and_end_%d:\n", cg.label_counter);
        cg.label_counter++;
        break;

    case binary_op::LOGICAL_OR:
        emit_comment(cg, "Logical OR");
        emit_instruction_reg_imm(cg, "cmp", x86_windows_register::RAX, 0);
        fprintf(cg.out_file, "\tjne .L_or_true_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "cmp", x86_windows_register::RCX, 0);
        fprintf(cg.out_file, "\tjne .L_or_true_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);
        fprintf(cg.out_file, "\tjmp .L_or_end_%d\n", cg.label_counter);
        fprintf(cg.out_file, ".L_or_true_%d:\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 1);
        fprintf(cg.out_file, ".L_or_end_%d:\n", cg.label_counter);
        cg.label_counter++;
        break;

    default:
        emit_comment(cg, "TODO: Binary operator %d", (int)binary->op);
        return false;
    }

    return true;
}

static bool generate_function_call_win(x86_windows_generator &cg, ast_expr_call *call) {
    // Check if this is a builtin function
    if (call->procedure->type == ast_node_type::EXPR_IDENTIFIER) {
        ast_expr_identifier *func_name = (ast_expr_identifier *)call->procedure;

        // Check for builtin functions
        if (strncmp(func_name->name, "print", func_name->name_len) == 0 && func_name->name_len == 5) {
            return generate_print_call_win(cg, call);
        }
        if (strncmp(func_name->name, "println", func_name->name_len) == 0 && func_name->name_len == 7) {
            return generate_println_call_win(cg, call);
        }
    }

    emit_comment(cg, "TODO: User-defined function call");
    return false;
}

static bool generate_print_call_win(x86_windows_generator &cg, ast_expr_call *call) {
    if (call->argument_count != 1) {
        return false;
    }

    // For now, only support string literals
    ast_node *arg = call->arguments[0];
    if (arg->type != ast_node_type::EXPR_LITERAL) {
        return false;
    }

    ast_expr_literal *str_literal = (ast_expr_literal *)arg;
    if (str_literal->type != literal_type::STRING) {
        return false;
    }

    emit_comment(cg, "print(\"%.*s\") - using WriteConsoleA", str_literal->value_len, str_literal->value);

    // Generate string constant
    static int string_counter = 0;
    fprintf(cg.out_file, "\t.section .rdata\n");
    fprintf(cg.out_file, ".LC%d:\n", string_counter);

    // Calculate actual string length (without quotes)
    const char *str_content = str_literal->value + 1; // Skip opening quote
    u32 content_len = str_literal->value_len - 2;     // Remove both quotes

    // Output the string with null terminator for Windows API
    fprintf(cg.out_file, "\t.string \"");
    for (u32 i = 0; i < content_len; i++) {
        char c = str_content[i];
        if (c == '\\' && i + 1 < content_len) {
            char next = str_content[i + 1];
            switch (next) {
            case 'n':
                fprintf(cg.out_file, "\\n");
                i++;
                break;
            case 't':
                fprintf(cg.out_file, "\\t");
                i++;
                break;
            case 'r':
                fprintf(cg.out_file, "\\r");
                i++;
                break;
            case '\\':
                fprintf(cg.out_file, "\\\\");
                i++;
                break;
            case '"':
                fprintf(cg.out_file, "\\\"");
                i++;
                break;
            default:
                fprintf(cg.out_file, "%c", c);
                break;
            }
        } else {
            fprintf(cg.out_file, "%c", c);
        }
    }
    fprintf(cg.out_file, "\"\n");

    // Store the string length as a constant
    fprintf(cg.out_file, ".LC%d_len = %u\n", string_counter, content_len);

    fprintf(cg.out_file, "\t.text\n");

    // Windows API call: WriteConsoleA(hConsoleOutput, lpBuffer, nNumberOfCharsToWrite, lpNumberOfCharsWritten,
    // lpReserved) We need to get stdout handle first with GetStdHandle

    emit_comment(cg, "Get stdout handle");
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RCX, -11); // STD_OUTPUT_HANDLE
    fprintf(cg.out_file, "\tcall GetStdHandle\n");                       // Returns handle in RAX
    emit_instruction_reg(cg, "push", x86_windows_register::RAX);         // Save handle

    emit_comment(cg, "Call WriteConsoleA");
    // Windows x64 calling convention: RCX, RDX, R8, R9, then stack
    emit_instruction_reg(cg, "pop", x86_windows_register::RCX);         // hConsoleOutput (stdout handle)
    fprintf(cg.out_file, "\tlea rdx, .LC%d[rip]\n", string_counter);    // lpBuffer
    fprintf(cg.out_file, "\tmov r8, .LC%d_len\n", string_counter);      // nNumberOfCharsToWrite
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::R9, 0);   // lpNumberOfCharsWritten (NULL)
    emit_instruction_reg_imm(cg, "sub", x86_windows_register::RSP, 32); // Shadow space
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);  // lpReserved (5th param on stack)
    fprintf(cg.out_file, "\tmov [rsp+32], rax\n");                      // Store 5th parameter
    fprintf(cg.out_file, "\tcall WriteConsoleA\n");
    emit_instruction_reg_imm(cg, "add", x86_windows_register::RSP, 32); // Clean up shadow space

    string_counter++;
    return true;
}

static bool generate_println_call_win(x86_windows_generator &cg, ast_expr_call *call) {
    // Print the string first
    if (!generate_print_call_win(cg, call)) return false;

    // Then print a newline
    emit_comment(cg, "Print newline");

    // Create a newline string in .rdata
    static int newline_counter = 0;
    fprintf(cg.out_file, "\t.section .rdata\n");
    fprintf(cg.out_file, ".newline%d:\n", newline_counter);
    fprintf(cg.out_file, "\t.string \"\\n\"\n");
    fprintf(cg.out_file, "\t.text\n");

    // Get stdout handle again
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RCX, -11); // STD_OUTPUT_HANDLE
    fprintf(cg.out_file, "\tcall GetStdHandle\n");
    emit_instruction_reg(cg, "push", x86_windows_register::RAX);

    // WriteConsoleA call for newline
    emit_instruction_reg(cg, "pop", x86_windows_register::RCX);            // hConsoleOutput
    fprintf(cg.out_file, "\tlea rdx, .newline%d[rip]\n", newline_counter); // lpBuffer
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::R8, 1);      // nNumberOfCharsToWrite
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::R9, 0);      // lpNumberOfCharsWritten (NULL)
    emit_instruction_reg_imm(cg, "sub", x86_windows_register::RSP, 32);    // Shadow space
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RAX, 0);     // lpReserved
    fprintf(cg.out_file, "\tmov [rsp+32], rax\n");
    fprintf(cg.out_file, "\tcall WriteConsoleA\n");
    emit_instruction_reg_imm(cg, "add", x86_windows_register::RSP, 32);

    newline_counter++;
    return true;
}

static bool generate_exit_call_win(x86_windows_generator &cg, int exit_code) {
    emit_comment(cg, "Exit with code %d", exit_code);
    emit_instruction_reg_imm(cg, "mov", x86_windows_register::RCX, exit_code); // Exit code in first parameter
    fprintf(cg.out_file, "\tcall ExitProcess\n");                              // Windows API exit
    return true;
}

// =============================================================================
// ASSEMBLY OUTPUT HELPERS
// =============================================================================

static void emit_comment(x86_windows_generator &cg, const char *comment, ...) {
    fprintf(cg.out_file, "\t# ");
    va_list args;
    va_start(args, comment);
    vfprintf(cg.out_file, comment, args);
    va_end(args);
    fprintf(cg.out_file, "\n");
}

static void emit_label(x86_windows_generator &cg, const char *label) {
    fprintf(cg.out_file, "%s:\n", label);
}

static void emit_directive(x86_windows_generator &cg, const char *directive) {
    fprintf(cg.out_file, "%s\n", directive);
}

static void emit_instruction(x86_windows_generator &cg, const char *instr) {
    fprintf(cg.out_file, "\t%s\n", instr);
}

static void emit_instruction_reg(x86_windows_generator &cg, const char *instr, x86_windows_register r) {
    fprintf(cg.out_file, "\t%s %s\n", instr, reg_name_64_win(r));
}

static void emit_instruction_reg_reg(x86_windows_generator &cg, const char *instr, x86_windows_register dst,
                                     x86_windows_register src) {
    fprintf(cg.out_file, "\t%s %s, %s\n", instr, reg_name_64_win(dst), reg_name_64_win(src));
}

static void emit_instruction_reg_imm(x86_windows_generator &cg, const char *instr, x86_windows_register r, i32 imm) {
    fprintf(cg.out_file, "\t%s %s, %d\n", instr, reg_name_64_win(r), imm);
}

static void emit_instruction_reg_mem(x86_windows_generator &cg, const char *instr, x86_windows_register r,
                                     x86_windows_register base, i32 offset) {
    if (offset == 0) {
        fprintf(cg.out_file, "\t%s %s, [%s]\n", instr, reg_name_64_win(r), reg_name_64_win(base));
    } else {
        fprintf(cg.out_file, "\t%s %s, [%s%+d]\n", instr, reg_name_64_win(r), reg_name_64_win(base), offset);
    }
}

static const char *reg_name_64_win(x86_windows_register r) {
    switch (r) {
    case x86_windows_register::RAX:
        return "rax";
    case x86_windows_register::RBX:
        return "rbx";
    case x86_windows_register::RCX:
        return "rcx";
    case x86_windows_register::RDX:
        return "rdx";
    case x86_windows_register::RSI:
        return "rsi";
    case x86_windows_register::RDI:
        return "rdi";
    case x86_windows_register::RBP:
        return "rbp";
    case x86_windows_register::RSP:
        return "rsp";
    case x86_windows_register::R8:
        return "r8";
    case x86_windows_register::R9:
        return "r9";
    case x86_windows_register::R10:
        return "r10";
    case x86_windows_register::R11:
        return "r11";
    case x86_windows_register::R12:
        return "r12";
    case x86_windows_register::R13:
        return "r13";
    case x86_windows_register::R14:
        return "r14";
    case x86_windows_register::R15:
        return "r15";
    default:
        return "???";
    }
}

static const char *reg_name_32_win(x86_windows_register r) {
    switch (r) {
    case x86_windows_register::RAX:
    case x86_windows_register::EAX:
        return "eax";
    case x86_windows_register::RBX:
    case x86_windows_register::EBX:
        return "ebx";
    case x86_windows_register::RCX:
    case x86_windows_register::ECX:
        return "ecx";
    case x86_windows_register::RDX:
    case x86_windows_register::EDX:
        return "edx";
    case x86_windows_register::RSI:
    case x86_windows_register::ESI:
        return "esi";
    case x86_windows_register::RDI:
    case x86_windows_register::EDI:
        return "edi";
    case x86_windows_register::RBP:
    case x86_windows_register::EBP:
        return "ebp";
    case x86_windows_register::RSP:
    case x86_windows_register::ESP:
        return "esp";
    case x86_windows_register::R8:
        return "r8d";
    case x86_windows_register::R9:
        return "r9d";
    case x86_windows_register::R10:
        return "r10d";
    case x86_windows_register::R11:
        return "r11d";
    case x86_windows_register::R12:
        return "r12d";
    case x86_windows_register::R13:
        return "r13d";
    case x86_windows_register::R14:
        return "r14d";
    case x86_windows_register::R15:
        return "r15d";
    default:
        return "???";
    }
}

static char *generate_label_win(x86_windows_generator &cg, const char *prefix) {
    char *label = (char *)arena_alloc(*cg.memory, 64);
    snprintf(label, 64, ".L%s%d", prefix, cg.label_counter++);
    return label;
}

static const char *builtin_type_size_suffix_win(builtin_type type) {
    switch (type) {
    case builtin_type::BOOL:
    case builtin_type::U8:
    case builtin_type::S8:
    case builtin_type::CHAR:
        return "b"; // byte
    case builtin_type::U16:
    case builtin_type::S16:
        return "w"; // word
    case builtin_type::U32:
    case builtin_type::S32:
    case builtin_type::F32:
        return "d"; // dword
    case builtin_type::U64:
    case builtin_type::S64:
    case builtin_type::F64:
    case builtin_type::USIZE:
    case builtin_type::SSIZE:
        return "q"; // qword
    default:
        return "q"; // default to 64-bit
    }
}

static const char *reg_name_for_type_win(x86_windows_register r, builtin_type type) {
    switch (builtin_type_size_suffix_win(type)[0]) {
    case 'b': // 8-bit registers would need separate handling
    case 'w': // 16-bit registers would need separate handling
    case 'd':
        return reg_name_32_win(r);
    case 'q':
    default:
        return reg_name_64_win(r);
    }
}
