#include "x86_generator.hpp"
#include "ast.hpp"
#include "defines.hpp"
#include "memory.hpp"
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>

// =============================================================================
// CODE GENERATION ENTRY POINTS
// =============================================================================

static bool generate_declaration(x86_generator &cg, ast_node *decl);
static bool generate_procedure(x86_generator &cg, ast_decl_procedure *proc);
static bool generate_statement(x86_generator &cg, ast_node *stmt);
static bool generate_expression(x86_generator &cg, ast_node *expr);
static bool generate_global_variable(x86_generator &cg, ast_decl_variable *var_decl);
static bool generate_literal(x86_generator &cg, ast_expr_literal *lit);
static bool generate_identifier(x86_generator &cg, ast_expr_identifier *ident);
static bool generate_binary_expression(x86_generator &cg, ast_expr_binary *binary);
static bool generate_procedure_call(x86_generator &cg, ast_expr_call *call);
static bool generate_print_call(x86_generator &cg, ast_expr_call *call);
static bool generate_println_call(x86_generator &cg, ast_expr_call *call);
static bool generate_exit_call(x86_generator &cg, int exit_code);
static char *generate_mangled_name(x86_generator &cg, const char **module_path, u32 path_len, const char *symbol_name,
                                   u32 symbol_len);

// =============================================================================
// ASSEMBLY OUTPUT HELPERS
// =============================================================================

// Register name helpers
static const char *reg_name_64(reg r);
static const char *reg_name_32(reg r);

static char *generate_label(x86_generator &cg, const char *prefix);

static const char *builtin_type_size_suffix(builtin_type type);
static const char *reg_name_for_type(reg r, builtin_type type);

extern const char *binary_op_to_string(binary_op op);

bool x86_gen_init(x86_generator &cg, arena &memory, FILE *out_file) {
    cg.memory = &memory;
    cg.out_file = out_file;
    cg.stack_offset = 0;
    cg.label_counter = 0;
    cg.current_procedure = nullptr;
    cg.in_procedure = false;

    return true;
}

void x86_gen_deinit(x86_generator &cg) {
    cg = {};
}

bool generate_x86(x86_generator &cg, ast_node *program) {
    if (!program || program->type != ast_node_type::TRANSLATION_UNIT) {
        return false;
    }

    ast_translation_unit *unit = (ast_translation_unit *)program;

    // Generate assembly header
    fprintf(cg.out_file, ".intel_syntax noprefix\n");
    fprintf(cg.out_file, ".text\n");
    fprintf(cg.out_file, "\t# Generated by our language compiler\n\n");

    // Add proper entry point
    fprintf(cg.out_file, ".global _start\n");
    fprintf(cg.out_file, "_start:\n");
    fprintf(cg.out_file, "\tcall main\n");
    fprintf(cg.out_file, "\tmov rdi, rax\n"); // Move return value to rdi for exit
    fprintf(cg.out_file, "\tmov rax, 60\n");  // sys_exit
    fprintf(cg.out_file, "\tsyscall\n\n");    // Exit with main's return value

    // Process all declarations
    for (u32 i = 0; i < unit->declaration_count; i++) {
        ast_node *decl = unit->declarations[i];

        if (decl->type == ast_node_type::DECL_PROCEDURE) {
            if (!generate_procedure(cg, (ast_decl_procedure *)decl)) {
                return false;
            }
        } else if (decl->type == ast_node_type::DECL_VARIABLE) {
            if (!generate_global_variable(cg, (ast_decl_variable *)decl)) {
                return false;
            }
        }
    }

    return true;
}

static bool generate_declaration(x86_generator &cg, ast_node *decl) {
    switch (decl->type) {
    case ast_node_type::DECL_PROCEDURE: {
        ast_decl_procedure *proc = (ast_decl_procedure *)decl;
        return generate_procedure(cg, proc);
    }

    case ast_node_type::DECL_VARIABLE: {
        // TODO: Global variables
        emit_comment(cg, "TODO: Global variable declarations");
        return true;
    }

    default:
        emit_comment(cg, "TODO: Other declaration types");
        return true;
    }
}

// static bool generate_procedure(x86_generator &cg, ast_decl_procedure *proc) {
//     // Determine the procedure name based on module context
//     char *proc_name;

//     if (cg.current_module_path && cg.current_module_depth > 0) {
//         // This is a procedure inside a module - generate mangled name
//         proc_name =
//             generate_mangled_name(cg, cg.current_module_path, cg.current_module_depth, proc->name, proc->name_len);
//         if (!proc_name) return false;
//     } else {
//         // This is a top-level procedure - use simple name
//         proc_name = (char *)arena_alloc(*cg.memory, proc->name_len + 1);
//         if (!proc_name) return false;
//         strncpy(proc_name, proc->name, proc->name_len);
//         proc_name[proc->name_len] = '\0';
//     }

//     cg.current_procedure = proc_name;
//     cg.in_procedure = true;
//     cg.stack_offset = 0;

//     // Procedure declaration without body (forward declaration)
//     if (!proc->body) {
//         emit_comment(cg, "Forward declaration - no code generated");
//         return true;
//     }

//     emit_comment(cg, "Procedure: %s", proc_name);

//     // Make procedure globally visible
//     fprintf(cg.out_file, ".global %s\n", proc_name);
//     emit_label(cg, proc_name);

//     // Procedure prologue
//     emit_comment(cg, "Procedure prologue");
//     emit_instruction_reg(cg, "push", reg::RBP);
//     emit_instruction_reg_reg(cg, "mov", reg::RBP, reg::RSP);

//     // Generate procedure body
//     if (!generate_statement(cg, proc->body)) {
//         return false;
//     }

//     // Procedure epilogue (in case there's no explicit return)
//     emit_comment(cg, "Procedure epilogue");
//     emit_instruction_reg_reg(cg, "mov", reg::RSP, reg::RBP);
//     emit_instruction_reg(cg, "pop", reg::RBP);
//     emit_instruction(cg, "ret");

//     cg.in_procedure = false;
//     cg.current_procedure = nullptr;

//     return true;
// }

static bool generate_procedure(x86_generator &cg, ast_decl_procedure *proc) {
    // Procedure name from token
    char proc_name[256];
    snprintf(proc_name, sizeof(proc_name), "%.*s", proc->name_len, proc->name);

    cg.current_procedure = proc_name;
    cg.in_procedure = true;
    cg.stack_offset = 0;

    // Procedure declaration without body (forward declaration)
    if (!proc->body) {
        emit_comment(cg, "Forward declaration - no code generated");
        return true;
    }

    emit_comment(cg, "Procedure: %s", proc_name);

    // Make procedure globally visible
    fprintf(cg.out_file, ".global %s\n", proc_name);
    emit_label(cg, proc_name);

    // Procedure prologue
    emit_comment(cg, "Procedure prologue");
    emit_instruction_reg(cg, "push", reg::RBP);              // Save old base pointer
    emit_instruction_reg_reg(cg, "mov", reg::RBP, reg::RSP); // Set up new base pointer

    // TODO: Allocate space for local variables
    // emit_instruction_reg_imm(cg, "sub", reg::RSP, local_var_space);

    // Generate procedure body
    if (!generate_statement(cg, proc->body)) {
        return false;
    }

    // Procedure epilogue (in case there's no explicit return)
    emit_comment(cg, "Procedure epilogue");
    emit_instruction_reg_reg(cg, "mov", reg::RSP, reg::RBP); // Restore stack pointer
    emit_instruction_reg(cg, "pop", reg::RBP);               // Restore base pointer
    emit_instruction(cg, "ret");                             // Return

    cg.in_procedure = false;
    cg.current_procedure = nullptr;

    return true;
}

static bool generate_statement(x86_generator &cg, ast_node *stmt) {
    if (!stmt) return true;

    switch (stmt->type) {
    case ast_node_type::STMT_COMPOUND: {
        ast_stmt_compound *compound = (ast_stmt_compound *)stmt;
        emit_comment(cg, "Compound statement");

        for (u32 i = 0; i < compound->statement_count; i++) {
            if (!generate_statement(cg, compound->statements[i])) {
                return false;
            }
        }
        return true;
    }

    case ast_node_type::STMT_RETURN: {
        ast_stmt_return *ret = (ast_stmt_return *)stmt;
        emit_comment(cg, "Return statement");

        if (ret->value) {
            // Generate code for return value (result should be in RAX)
            if (!generate_expression(cg, ret->value)) {
                return false;
            }
            // Result is already in RAX, which is the return register
        } else {
            // Return void - set RAX to 0
            emit_instruction_reg_imm(cg, "mov", reg::RAX, 0);
        }

        // Jump to procedure epilogue
        emit_instruction_reg_reg(cg, "mov", reg::RSP, reg::RBP);
        emit_instruction_reg(cg, "pop", reg::RBP);
        emit_instruction(cg, "ret");
        return true;
    }

    case ast_node_type::STMT_EXPRESSION: {
        ast_stmt_expression *expr_stmt = (ast_stmt_expression *)stmt;
        emit_comment(cg, "Expression statement");
        return generate_expression(cg, expr_stmt->expression);
    }

    case ast_node_type::STMT_IF: {
        ast_stmt_if *if_stmt = (ast_stmt_if *)stmt;
        emit_comment(cg, "If statement");

        char *else_label = generate_label(cg, "else");
        char *end_label = generate_label(cg, "endif");

        // Generate condition
        if (!generate_expression(cg, if_stmt->condition)) {
            return false;
        }

        // Test result and jump if false
        emit_instruction_reg_imm(cg, "cmp", reg::RAX, 0);
        fprintf(cg.out_file, "\tje %s\n", else_label);

        // Generate then block
        if (!generate_statement(cg, if_stmt->then_stmt)) {
            return false;
        }

        if (if_stmt->else_stmt) {
            fprintf(cg.out_file, "\tjmp %s\n", end_label);
            emit_label(cg, else_label);
            if (!generate_statement(cg, if_stmt->else_stmt)) {
                return false;
            }
            emit_label(cg, end_label);
        } else {
            emit_label(cg, else_label);
        }

        return true;
    }

    default:
        emit_comment(cg, "TODO: Statement type %d", (int)stmt->type);
        return true;
    }
}

static bool generate_expression(x86_generator &cg, ast_node *expr) {
    if (!expr) {
        return false;
    }

    switch (expr->type) {
    case ast_node_type::EXPR_CALL:
        return generate_procedure_call(cg, (ast_expr_call *)expr);
    case ast_node_type::EXPR_LITERAL:
        return generate_literal(cg, (ast_expr_literal *)expr);
    case ast_node_type::EXPR_IDENTIFIER:
        return generate_identifier(cg, (ast_expr_identifier *)expr);
    case ast_node_type::EXPR_BINARY:
        return generate_binary_expression(cg, (ast_expr_binary *)expr);
    default:
        return false;
    }
}

static bool generate_global_variable(x86_generator &cg, ast_decl_variable *var_decl) {
    char var_name[256];
    snprintf(var_name, sizeof(var_name), "%.*s", var_decl->name_len, var_decl->name);

    emit_comment(cg, "Global variable: %s", var_name);

    // Switch to data section
    fprintf(cg.out_file, ".section .data\n");

    // Make variable globally visible
    fprintf(cg.out_file, ".global %s\n", var_name);
    emit_label(cg, var_name);

    // Initialize with value if present
    if (var_decl->initializer && var_decl->initializer->type == ast_node_type::EXPR_LITERAL) {
        ast_expr_literal *lit = (ast_expr_literal *)var_decl->initializer;

        switch (lit->type) {
        case literal_type::INTEGER: {
            char value_str[32];
            snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
            i32 value = atoi(value_str);
            fprintf(cg.out_file, "\t.long %d\n", value);
            break;
        }
        case literal_type::STRING: {
            // String literals go in .rodata
            fprintf(cg.out_file, ".section .rodata\n");
            fprintf(cg.out_file, "\t.string ");

            // Print the string literal with quotes
            for (u32 i = 0; i < lit->value_len; i++) {
                fputc(lit->value[i], cg.out_file);
            }
            fprintf(cg.out_file, "\n");
            break;
        }
        case literal_type::BOOLEAN: {
            char value_str[8];
            snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
            bool is_true = (strncmp(value_str, "true", 4) == 0);
            fprintf(cg.out_file, "\t.byte %d\n", is_true ? 1 : 0);
            break;
        }
        default:
            fprintf(cg.out_file, "\t.long 0\n"); // Default initialization
            break;
        }
    } else {
        // Default initialization
        fprintf(cg.out_file, "\t.long 0\n");
    }

    // Switch back to text section
    fprintf(cg.out_file, ".section .text\n");

    return true;
}

static bool generate_literal(x86_generator &cg, ast_expr_literal *lit) {
    switch (lit->type) {
    case literal_type::INTEGER: {
        char value_str[32];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
        i32 value = atoi(value_str);

        emit_comment(cg, "Integer literal: %d", value);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, value);
        return true;
    }

    case literal_type::BOOLEAN: {
        // Handle true/false literals
        char value_str[8];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);
        bool is_true = (strncmp(value_str, "true", 4) == 0);

        emit_comment(cg, "Boolean literal: %s", is_true ? "true" : "false");
        emit_instruction_reg_imm(cg, "mov", reg::RAX, is_true ? 1 : 0);
        return true;
    }

    case literal_type::STRING: {
        // For string literals in expressions, we need to create a string constant
        emit_comment(cg, "String literal: %.*s", lit->value_len, lit->value);

        static int string_literal_counter = 0;

        // Generate string constant in .rodata section
        fprintf(cg.out_file, "\t.section .rodata\n");
        fprintf(cg.out_file, ".LS%d:\n", string_literal_counter);

        // Remove quotes and handle escape sequences
        const char *str_content = lit->value + 1; // Skip opening quote
        u32 content_len = lit->value_len - 2;     // Remove both quotes

        fprintf(cg.out_file, "\t.string \"");
        for (u32 i = 0; i < content_len; i++) {
            char c = str_content[i];
            if (c == '\\' && i + 1 < content_len) {
                char next = str_content[i + 1];
                switch (next) {
                case 'n':
                    fprintf(cg.out_file, "\\n");
                    i++;
                    break;
                case 't':
                    fprintf(cg.out_file, "\\t");
                    i++;
                    break;
                case 'r':
                    fprintf(cg.out_file, "\\r");
                    i++;
                    break;
                case '\\':
                    fprintf(cg.out_file, "\\\\");
                    i++;
                    break;
                case '"':
                    fprintf(cg.out_file, "\\\"");
                    i++;
                    break;
                default:
                    fprintf(cg.out_file, "%c", c);
                    break;
                }
            } else {
                fprintf(cg.out_file, "%c", c);
            }
        }
        fprintf(cg.out_file, "\"\n");

        fprintf(cg.out_file, "\t.text\n");

        // Load address of string into RAX
        fprintf(cg.out_file, "\tlea rax, .LS%d[rip]\n", string_literal_counter);

        string_literal_counter++;
        return true;
    }

    case literal_type::CHARACTER: {
        // Handle character literals
        char value_str[8];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);

        // Simple character handling (assumes single char between quotes)
        char char_value = 0;
        if (lit->value_len >= 3) {      // At least 'x'
            char_value = lit->value[1]; // Skip opening quote
        }

        emit_comment(cg, "Character literal: %c (%d)", char_value, (int)char_value);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, (i32)char_value);
        return true;
    }

    case literal_type::FLOAT: {
        // Handle floating point literals (basic implementation)
        char value_str[32];
        snprintf(value_str, sizeof(value_str), "%.*s", lit->value_len, lit->value);

        emit_comment(cg, "Float literal: %s (TODO: proper float handling)", value_str);
        // For now, just convert to int (this is a placeholder)
        i32 int_value = (i32)atof(value_str);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, int_value);
        return true;
    }

    default:
        emit_comment(cg, "TODO: Unsupported literal type %d", (int)lit->type);
        return false;
    }
}

static bool generate_identifier(x86_generator &cg, ast_expr_identifier *ident) {
    char name[256];
    snprintf(name, sizeof(name), "%.*s", ident->name_len, ident->name);

    emit_comment(cg, "Variable access: %s", name);

    // TODO: This is where you'd look up the variable in a symbol table
    // and determine if it's:
    // 1. A local variable (access via [rbp + offset])
    // 2. A global variable (access via symbol name)
    // 3. A parameter (access via [rbp + offset])

    // For now, assume it's a global variable
    fprintf(cg.out_file, "\tmov rax, [%s]\n", name);

    return true;
}

static bool generate_binary_expression(x86_generator &cg, ast_expr_binary *binary) {
    emit_comment(cg, "Binary expression: %s", binary_op_to_string(binary->op));

    // Generate right operand first
    if (!generate_expression(cg, binary->right)) {
        return false;
    }
    emit_instruction_reg(cg, "push", reg::RAX); // Save right operand

    // Generate left operand
    if (!generate_expression(cg, binary->left)) {
        return false;
    }

    // Pop right operand into RCX
    emit_instruction_reg(cg, "pop", reg::RCX);

    // Perform operation (left in RAX, right in RCX)
    switch (binary->op) {
    case binary_op::ADD:
        emit_instruction_reg_reg(cg, "add", reg::RAX, reg::RCX);
        break;

    case binary_op::SUB:
        emit_instruction_reg_reg(cg, "sub", reg::RAX, reg::RCX);
        break;

    case binary_op::MUL:
        emit_instruction_reg_reg(cg, "imul", reg::RAX, reg::RCX);
        break;

    case binary_op::DIV:
        // x86 division is more complex - need to clear RDX and use idiv
        emit_comment(cg, "Division: clear RDX and divide");
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 0); // Clear upper 64 bits
        fprintf(cg.out_file, "\tidiv rcx\n");             // Signed divide RAX by RCX, result in RAX
        break;

    case binary_op::MOD:
        // Modulo is similar to division, but result is in RDX
        emit_comment(cg, "Modulo: clear RDX and divide, result in RDX");
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 0);
        fprintf(cg.out_file, "\tidiv rcx\n");
        emit_instruction_reg_reg(cg, "mov", reg::RAX, reg::RDX); // Move remainder to RAX
        break;

    case binary_op::EQ:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0); // Assume false
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1); // True value
        fprintf(cg.out_file, "\tcmove rax, rdx\n");       // Move 1 to RAX if equal
        break;

    case binary_op::NE:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0); // Assume false
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1); // True value
        fprintf(cg.out_file, "\tcmovne rax, rdx\n");      // Move 1 to RAX if not equal
        break;

    case binary_op::LT:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1);
        fprintf(cg.out_file, "\tcmovl rax, rdx\n"); // Move 1 if less than
        break;

    case binary_op::LE:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1);
        fprintf(cg.out_file, "\tcmovle rax, rdx\n"); // Move 1 if less than or equal
        break;

    case binary_op::GT:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1);
        fprintf(cg.out_file, "\tcmovg rax, rdx\n"); // Move 1 if greater than
        break;

    case binary_op::GE:
        emit_instruction_reg_reg(cg, "cmp", reg::RAX, reg::RCX);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0);
        emit_instruction_reg_imm(cg, "mov", reg::RDX, 1);
        fprintf(cg.out_file, "\tcmovge rax, rdx\n"); // Move 1 if greater than or equal
        break;

    case binary_op::LOGICAL_AND:
        // Short-circuit evaluation: if left is false, result is false
        emit_comment(cg, "Logical AND");
        emit_instruction_reg_imm(cg, "cmp", reg::RAX, 0);
        fprintf(cg.out_file, "\tje .L_and_false_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "cmp", reg::RCX, 0);
        fprintf(cg.out_file, "\tje .L_and_false_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 1); // Both true
        fprintf(cg.out_file, "\tjmp .L_and_end_%d\n", cg.label_counter);
        fprintf(cg.out_file, ".L_and_false_%d:\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0); // At least one false
        fprintf(cg.out_file, ".L_and_end_%d:\n", cg.label_counter);
        cg.label_counter++;
        break;

    case binary_op::LOGICAL_OR:
        // Short-circuit evaluation: if left is true, result is true
        emit_comment(cg, "Logical OR");
        emit_instruction_reg_imm(cg, "cmp", reg::RAX, 0);
        fprintf(cg.out_file, "\tjne .L_or_true_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "cmp", reg::RCX, 0);
        fprintf(cg.out_file, "\tjne .L_or_true_%d\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 0); // Both false
        fprintf(cg.out_file, "\tjmp .L_or_end_%d\n", cg.label_counter);
        fprintf(cg.out_file, ".L_or_true_%d:\n", cg.label_counter);
        emit_instruction_reg_imm(cg, "mov", reg::RAX, 1); // At least one true
        fprintf(cg.out_file, ".L_or_end_%d:\n", cg.label_counter);
        cg.label_counter++;
        break;

    default:
        emit_comment(cg, "TODO: Binary operator %d", (int)binary->op);
        return false;
    }

    return true;
}

static bool generate_procedure_call(x86_generator &cg, ast_expr_call *call) {

    if (call->procedure->type == ast_node_type::EXPR_IDENTIFIER) {
        // Regular function call: func()
        ast_expr_identifier *func_name = (ast_expr_identifier *)call->procedure;

        // Check for builtin functions
        if (strncmp(func_name->name, "print", func_name->name_len) == 0 && func_name->name_len == 5) {
            return generate_print_call(cg, call);
        }
        if (strncmp(func_name->name, "println", func_name->name_len) == 0 && func_name->name_len == 7) {
            return generate_println_call(cg, call);
        }

        // User-defined function call
        emit_comment(cg, "Call %.*s", func_name->name_len, func_name->name);
        fprintf(cg.out_file, "\tcall %.*s\n", func_name->name_len, func_name->name);
        return true;

    } else if (call->procedure->type == ast_node_type::EXPR_MEMBER_ACCESS) {
        // Module function call: module.func()
        ast_expr_member_access *member_access = (ast_expr_member_access *)call->procedure;

        if (member_access->is_module_access) {
            // Check if it's a builtin function accessed through module
            if (strncmp(member_access->member, "print", member_access->member_len) == 0 &&
                member_access->member_len == 5) {
                return generate_print_call(cg, call);
            }
            if (strncmp(member_access->member, "println", member_access->member_len) == 0 &&
                member_access->member_len == 7) {
                return generate_println_call(cg, call);
            }

            // For module.func(), treat as just func() for now
            // In the future, you might want to mangle the name: module_func
            emit_comment(cg, "Call %.*s (from module)", member_access->member_len, member_access->member);
            fprintf(cg.out_file, "\tcall %.*s\n", member_access->member_len, member_access->member);
            return true;
        } else {
            // Object method call - not yet implemented
            emit_comment(cg, "TODO: Object method calls not yet supported");
            return false;
        }
    } else {
        emit_comment(cg, "TODO: Unknown procedure call type");
        return false;
    }
}

static bool generate_print_call(x86_generator &cg, ast_expr_call *call) {
    if (call->argument_count != 1) return false;

    // For now, only support string literals
    ast_node *arg = call->arguments[0];
    if (arg->type != ast_node_type::EXPR_LITERAL) return false;

    ast_expr_literal *str_literal = (ast_expr_literal *)arg;
    if (str_literal->type != literal_type::STRING) return false;

    emit_comment(cg, "print(\"%.*s\") - using write syscall", str_literal->value_len, str_literal->value);

    // Generate string constant
    static int string_counter = 0;
    fprintf(cg.out_file, "\t.section .rodata\n");
    fprintf(cg.out_file, ".LC%d:\n", string_counter);

    // Calculate actual string length (without quotes)
    const char *str_content = str_literal->value + 1; // Skip opening quote
    u32 content_len = str_literal->value_len - 2;     // Remove both quotes

    // Output the string bytes directly (no null terminator needed for write syscall)
    fprintf(cg.out_file, "\t.ascii \"");
    for (u32 i = 0; i < content_len; i++) {
        char c = str_content[i];
        if (c == '\\' && i + 1 < content_len) {
            // Handle escape sequences
            char next = str_content[i + 1];
            switch (next) {
            case 'n':
                fprintf(cg.out_file, "\\n");
                i++;
                break;
            case 't':
                fprintf(cg.out_file, "\\t");
                i++;
                break;
            case 'r':
                fprintf(cg.out_file, "\\r");
                i++;
                break;
            case '\\':
                fprintf(cg.out_file, "\\\\");
                i++;
                break;
            case '"':
                fprintf(cg.out_file, "\\\"");
                i++;
                break;
            default:
                fprintf(cg.out_file, "%c", c);
                break;
            }
        } else {
            fprintf(cg.out_file, "%c", c);
        }
    }
    fprintf(cg.out_file, "\"\n");

    // Store the string length as a constant
    fprintf(cg.out_file, ".LC%d_len = %u\n", string_counter, content_len);

    fprintf(cg.out_file, "\t.text\n");

    // Linux write syscall: write(fd, buf, count)
    // System call number 1 (sys_write)
    // rdi = file descriptor (1 = stdout)
    // rsi = buffer pointer
    // rdx = byte count
    // rax = syscall number

    emit_comment(cg, "Setup write syscall");
    fprintf(cg.out_file, "\tmov rax, 1\n");                          // sys_write
    fprintf(cg.out_file, "\tmov rdi, 1\n");                          // stdout
    fprintf(cg.out_file, "\tlea rsi, .LC%d[rip]\n", string_counter); // string address
    fprintf(cg.out_file, "\tmov rdx, .LC%d_len\n", string_counter);  // string length
    fprintf(cg.out_file, "\tsyscall\n");                             // invoke system call

    string_counter++;
    return true;
}

static bool generate_println_call(x86_generator &cg, ast_expr_call *call) {
    // Print the string first
    if (!generate_print_call(cg, call)) return false;

    // Then print a newline
    emit_comment(cg, "Print newline");

    // Create a newline character in .rodata
    static int newline_counter = 0;
    fprintf(cg.out_file, "\t.section .rodata\n");
    fprintf(cg.out_file, ".newline%d:\n", newline_counter);
    fprintf(cg.out_file, "\t.ascii \"\\n\"\n");
    fprintf(cg.out_file, "\t.text\n");

    // Write syscall for newline
    fprintf(cg.out_file, "\tmov rax, 1\n");                                // sys_write
    fprintf(cg.out_file, "\tmov rdi, 1\n");                                // stdout
    fprintf(cg.out_file, "\tlea rsi, .newline%d[rip]\n", newline_counter); // newline address
    fprintf(cg.out_file, "\tmov rdx, 1\n");                                // 1 byte
    fprintf(cg.out_file, "\tsyscall\n");                                   // invoke system call

    newline_counter++;
    return true;
}

static bool generate_exit_call(x86_generator &cg, int exit_code) {
    emit_comment(cg, "Exit with code %d", exit_code);
    fprintf(cg.out_file, "\tmov rax, 60\n");            // sys_exit
    fprintf(cg.out_file, "\tmov rdi, %d\n", exit_code); // exit code
    fprintf(cg.out_file, "\tsyscall\n");                // invoke system call
    return true;
}

static char *generate_mangled_name(x86_generator &cg, const char **module_path, u32 path_len, const char *symbol_name,
                                   u32 symbol_len) {
    // Calculate total length needed
    u32 total_len = symbol_len;
    for (u32 i = 0; i < path_len; i++) {
        total_len += strlen(module_path[i]) + 1; // +1 for underscore
    }

    char *mangled = (char *)arena_alloc(*cg.memory, total_len + 1);
    if (!mangled) return nullptr;

    // Build the mangled name: module1_module2_symbol
    mangled[0] = '\0';
    for (u32 i = 0; i < path_len; i++) {
        strcat(mangled, module_path[i]);
        strcat(mangled, "_");
    }
    strncat(mangled, symbol_name, symbol_len);

    return mangled;
}

// =============================================================================
// ASSEMBLY OUTPUT HELPERS
// =============================================================================

void emit_comment(x86_generator &cg, const char *comment, ...) {
    fprintf(cg.out_file, "\t# ");
    va_list args;
    va_start(args, comment);
    vfprintf(cg.out_file, comment, args);
    va_end(args);
    fprintf(cg.out_file, "\n");
}

void emit_label(x86_generator &cg, const char *label) {
    fprintf(cg.out_file, "%s:\n", label);
}

void emit_directive(x86_generator &cg, const char *directive) {
    fprintf(cg.out_file, "%s\n", directive);
}

void emit_instruction(x86_generator &cg, const char *instr) {
    fprintf(cg.out_file, "\t%s\n", instr);
}

void emit_instruction_reg(x86_generator &cg, const char *instr, reg r) {
    fprintf(cg.out_file, "\t%s %s\n", instr, reg_name_64(r));
}

void emit_instruction_reg_reg(x86_generator &cg, const char *instr, reg dst, reg src) {
    fprintf(cg.out_file, "\t%s %s, %s\n", instr, reg_name_64(dst), reg_name_64(src));
}

void emit_instruction_reg_imm(x86_generator &cg, const char *instr, reg r, i32 imm) {
    fprintf(cg.out_file, "\t%s %s, %d\n", instr, reg_name_64(r), imm);
}

void emit_instruction_reg_mem(x86_generator &cg, const char *instr, reg r, reg base, i32 offset) {
    if (offset == 0) {
        fprintf(cg.out_file, "\t%s %s, [%s]\n", instr, reg_name_64(r), reg_name_64(base));
    } else {
        fprintf(cg.out_file, "\t%s %s, [%s%+d]\n", instr, reg_name_64(r), reg_name_64(base), offset);
    }
}

static const char *reg_name_64(reg r) {
    switch (r) {
    case reg::RAX:
        return "rax";
    case reg::RBX:
        return "rbx";
    case reg::RCX:
        return "rcx";
    case reg::RDX:
        return "rdx";
    case reg::RSI:
        return "rsi";
    case reg::RDI:
        return "rdi";
    case reg::RBP:
        return "rbp";
    case reg::RSP:
        return "rsp";
    case reg::R8:
        return "r8";
    case reg::R9:
        return "r9";
    case reg::R10:
        return "r10";
    case reg::R11:
        return "r11";
    case reg::R12:
        return "r12";
    case reg::R13:
        return "r13";
    case reg::R14:
        return "r14";
    case reg::R15:
        return "r15";
    default:
        return "???";
    }
}

static const char *reg_name_32(reg r) {
    switch (r) {
    case reg::RAX:
    case reg::EAX:
        return "eax";
    case reg::RBX:
    case reg::EBX:
        return "ebx";
    case reg::RCX:
    case reg::ECX:
        return "ecx";
    case reg::RDX:
    case reg::EDX:
        return "edx";
    case reg::RSI:
    case reg::ESI:
        return "esi";
    case reg::RDI:
    case reg::EDI:
        return "edi";
    case reg::RBP:
    case reg::EBP:
        return "ebp";
    case reg::RSP:
    case reg::ESP:
        return "esp";
    case reg::R8:
        return "r8d";
    case reg::R9:
        return "r9d";
    case reg::R10:
        return "r10d";
    case reg::R11:
        return "r11d";
    case reg::R12:
        return "r12d";
    case reg::R13:
        return "r13d";
    case reg::R14:
        return "r14d";
    case reg::R15:
        return "r15d";
    default:
        return "???";
    }
}

static char *generate_label(x86_generator &cg, const char *prefix) {
    char *label = (char *)arena_alloc(*cg.memory, 64);
    snprintf(label, 64, ".L%s%d", prefix, cg.label_counter++);
    return label;
}

static const char *builtin_type_size_suffix(builtin_type type) {
    switch (type) {
    case builtin_type::BOOL:
    case builtin_type::U8:
    case builtin_type::S8:
    case builtin_type::CHAR:
        return "b"; // byte
    case builtin_type::U16:
    case builtin_type::S16:
        return "w"; // word
    case builtin_type::U32:
    case builtin_type::S32:
    case builtin_type::F32:
        return "d"; // dword
    case builtin_type::U64:
    case builtin_type::S64:
    case builtin_type::F64:
    case builtin_type::USIZE:
    case builtin_type::SSIZE:
        return "q"; // qword
    default:
        return "q"; // default to 64-bit
    }
}

static const char *reg_name_for_type(reg r, builtin_type type) {
    switch (builtin_type_size_suffix(type)[0]) {
    case 'b': // 8-bit registers would need separate handling
    case 'w': // 16-bit registers would need separate handling
    case 'd':
        return reg_name_32(r);
    case 'q':
    default:
        return reg_name_64(r);
    }
}
